### ISSUE TITLE
API 27 error

### ISSUE THREAD

**Issue by hexilon** [NetEase-Object-Storage/nos-java-sdk#2]
java.lang.NoSuchMethodError: No virtual method setDefaultMaxPerRoute(I)V in class Lorg/apache/http/impl/conn/tsccm/ThreadSafeClientConnManager; or its super classes (declaration of 'org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager' appears in /system/framework/org.apache.http.legacy.boot.jar)
        at com.netease.cloud.http.ConnectionManagerFactory.createThreadSafeClientConnManager(ConnectionManagerFactory.java:13)
        at com.netease.cloud.http.HttpClientFactory.createHttpClient(HttpClientFactory.java:54)
        at com.netease.cloud.http.NeteaseHttpClient.<init>(NeteaseHttpClient.java:80)
        at com.netease.cloud.WebServiceClient.<init>(WebServiceClient.java:42)
        at com.netease.cloud.services.nos.NosClient.<init>(NosClient.java:190)

**Comment by Future2100** [comment]
这个问题是不同的sdk的版本导致的
